In [369]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler

from sklearn.preprocessing import RobustScaler, StandardScaler
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split

from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import PolynomialFeatures

from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn import linear_model 

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import ExtraTreesRegressor

from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import BayesianRidge

In [370]:
train_df = pd.read_csv('../data/final_diamonds_train.csv', index_col=[0])
train_df.head()

price  carat  depth  table     x     y     z  city_Amsterdam  city_Antwerp  \
0   3733   1.01   65.2   56.0  6.23  6.19  4.05               1             0   
1   9452   1.51   65.0   64.0  7.10  7.03  4.59               1             0   
2  12765   2.00   65.2   56.0  7.92  7.87  5.15               0             0   
3  17713   1.99   60.5   63.0  8.20  8.11  4.93               0             0   
4   2268   0.70   65.0   56.0  5.60  5.50  3.61               0             0   

   city_Dubai  ...  color_I  color_J  clarity_I1  clarity_IF  clarity_SI1  \
0           0  ...        0        0           0           0            0   
1           0  ...        0        0           0           0            0   
2           0  ...        0        0           0           0            0   
3           0  ...        0        0           0           0            0   
4           0  ...        0        0           0           0            0   

   clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2  
0            0            0            1             0             0  
1            0            0            1             0             0  
2            0            0            1             0             0  
3            0            0            1             0             0  
4            0            0            1             0             0  

[5 rows x 40 columns]

In [371]:
# creating X and y

X = train_df.drop('price', axis=1)
X.head()

carat  depth  table     x     y     z  city_Amsterdam  city_Antwerp  \
0   1.01   65.2   56.0  6.23  6.19  4.05               1             0   
1   1.51   65.0   64.0  7.10  7.03  4.59               1             0   
2   2.00   65.2   56.0  7.92  7.87  5.15               0             0   
3   1.99   60.5   63.0  8.20  8.11  4.93               0             0   
4   0.70   65.0   56.0  5.60  5.50  3.61               0             0   

   city_Dubai  city_Kimberly  ...  color_I  color_J  clarity_I1  clarity_IF  \
0           0              0  ...        0        0           0           0   
1           0              0  ...        0        0           0           0   
2           0              0  ...        0        0           0           0   
3           0              0  ...        0        0           0           0   
4           0              0  ...        0        0           0           0   

   clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0            0            0            0            1             0   
1            0            0            0            1             0   
2            0            0            0            1             0   
3            0            0            0            1             0   
4            0            0            0            1             0   

   clarity_VVS2  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 39 columns]

In [372]:
y = train_df['price']
y

0         3733
1         9452
2        12765
3        17713
4         2268
         ...  
40450     3193
40451    15898
40452      666
40453     1945
40454     6521
Name: price, Length: 40455, dtype: int64

In [373]:
#  Data scaling
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

In [374]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [375]:
'''
# Create polynomial features
poly_features = PolynomialFeatures(2)  # Set the desired degree of the polynomial
X_train_poly = poly_features.fit_transform(X_train)
X_test_poly = poly_features.transform(X_test)
'''

'\n# Create polynomial features\npoly_features = PolynomialFeatures(2)  # Set the desired degree of the polynomial\nX_train_poly = poly_features.fit_transform(X_train)\nX_test_poly = poly_features.transform(X_test)\n'

In [376]:
%%time

# Create polynomial features
poly_features = PolynomialFeatures(2)  # Set the desired degree of the polynomial
X_poly = poly_features.fit_transform(X_train)
#X_test_poly = poly_features.transform(X_test)

CPU times: total: 188 ms
Wall time: 368 ms


In [377]:
'''
%%time
# Train the model

model = DecisionTreeRegressor()
model.fit(X_train_poly, y_train)
'''

'\n%%time\n# Train the model\n\nmodel = DecisionTreeRegressor()\nmodel.fit(X_train_poly, y_train)\n'

In [378]:
%%time
# Train the model

model = BayesianRidge()
model.fit(X, y)

CPU times: total: 516 ms
Wall time: 208 ms


BayesianRidge()

In [379]:
%%time

# Model predictions

predictions = model.predict(X_test)
predictions

CPU times: total: 0 ns
Wall time: 3.4 ms


array([5188.64683316, 3145.76749935, 1932.2052564 , ..., 6946.98534882,
       6074.57203322,  433.87748247])

In [380]:
# RMSE

tricky_error = round(mean_squared_error(y_test, predictions)**0.5, 5)
tricky_error

1135.32498

In [381]:
%%time

# Model training

weights = model.fit(X_train, y_train)
weights

CPU times: total: 500 ms
Wall time: 134 ms


BayesianRidge()

In [382]:
%%time

# Model predictions

predictions = model.predict(X_test)
predictions

CPU times: total: 0 ns
Wall time: 7.54 ms


array([5169.1907901 , 3127.59213213, 1953.94003028, ..., 6932.44973323,
       6105.32271087,  454.76379807])

In [383]:
# RMSE

real_error = round(mean_squared_error(y_test, predictions)**0.5, 5)
real_error

1137.31983

In [273]:
'''
# Make predictions
y_pred = model.predict(X)
y_pred
'''

'\n# Make predictions\ny_pred = model.predict(X)\ny_pred\n'

In [253]:
'''
# Calculate RMSE
rmse = np.sqrt(mean_squared_error(y, y_pred))
print("RMSE:", rmse)
'''

RMSE: 1124.93798705494


### Test set

In [274]:
# test diamond ML

test_df = pd.read_csv('../data/final_diamonds_test.csv',index_col=[0])
test_df.head()

carat  depth  table     x     y     z  city_Amsterdam  city_Antwerp  \
0   0.79   62.7   60.0  5.82  5.89  3.67               1             0   
1   1.20   61.0   57.0  6.81  6.89  4.18               0             0   
2   1.57   62.2   61.0  7.38  7.32  4.57               0             0   
3   0.90   63.8   54.0  6.09  6.13  3.90               0             0   
4   0.50   62.9   58.0  5.05  5.09  3.19               1             0   

   city_Dubai  city_Kimberly  ...  color_I  color_J  clarity_I1  clarity_IF  \
0           0              0  ...        0        0           0           0   
1           0              0  ...        0        1           0           0   
2           0              1  ...        0        0           0           0   
3           0              1  ...        0        0           0           0   
4           0              0  ...        0        0           0           0   

   clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0            1            0            0            0             0   
1            0            0            1            0             0   
2            1            0            0            0             0   
3            1            0            0            0             0   
4            0            0            1            0             0   

   clarity_VVS2  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 39 columns]

In [275]:
# Create polynomial features

poly_features = PolynomialFeatures(2)
test_poly = poly_features.fit_transform(test_df)

In [276]:
%%time
# Train the model
model = BayesianRidge()
model.fit(X, y)

CPU times: total: 24 s
Wall time: 31.4 s


RandomForestRegressor()

In [277]:
# Model predictions

predictions = model.predict(test_df)
predictions

array([2988.64, 5382.29, 9700.49, ..., 2942.73, 2186.19,  836.62])

In [278]:
# Create a dataframe with the predicted price
predictions_df = pd.DataFrame({'price': predictions})
predictions_df

price
0      2988.64
1      5382.29
2      9700.49
3      4219.30
4      1705.32
...        ...
13480  1691.50
13481  2438.86
13482  2942.73
13483  2186.19
13484   836.62

[13485 rows x 1 columns]

In [279]:
# Set the name of the index as 'id'
predictions_df = predictions_df.rename_axis('id')
predictions_df.head()

price
id         
0   2988.64
1   5382.29
2   9700.49
3   4219.30
4   1705.32

In [280]:
predictions_df.to_csv('../predictions/predict-22.csv')

In [179]:
#predictions_df.to_csv('../predictions/predict-19.csv')