In [140]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import RobustScaler, StandardScaler
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split

from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from sklearn.tree import DecisionTreeRegressor

from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn import linear_model 

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import ExtraTreesRegressor

from sklearn.neighbors import KNeighborsRegressor
from sklearn.gaussian_process import GaussianProcessRegressor

# para calcular las métricas
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score 
from sklearn.metrics import precision_score 
from sklearn.metrics import recall_score 
from sklearn.metrics import f1_score 
from sklearn.metrics import cohen_kappa_score
from sklearn import metrics

In [132]:
'''
def metricas(y_test, y_train, y_test_pred, y_train_pred, tipo_modelo):
    
    
    resultados = {'MAE': [metrics.mean_absolute_error(y_test, y_test_pred), metrics.mean_absolute_error(y_train, y_train_pred)],
                'MSE': [metrics.mean_squared_error(y_test, y_test_pred), metrics.mean_squared_error(y_train, y_train_pred)],
                'RMSE': [np.sqrt(metrics.mean_squared_error(y_test, y_test_pred)), np.sqrt(metrics.mean_squared_error(y_train, y_train_pred))],
                'R2':  [metrics.r2_score(y_test, y_test_pred), metrics.r2_score(y_train, y_train_pred)],
                 "set": ["test", "train"]}
    df = pd.DataFrame(resultados)
    df["modelo"] = tipo_modelo
    return df
'''

### Train set

In [134]:
train_df = pd.read_csv('../data/final_diamonds_train.csv', index_col=[0])
train_df.head()

price  carat  depth  table     x     y     z  city_Amsterdam  city_Antwerp  \
0   3733   1.01   65.2   56.0  6.23  6.19  4.05               1             0   
1   9452   1.51   65.0   64.0  7.10  7.03  4.59               1             0   
2  12765   2.00   65.2   56.0  7.92  7.87  5.15               0             0   
3  17713   1.99   60.5   63.0  8.20  8.11  4.93               0             0   
4   2268   0.70   65.0   56.0  5.60  5.50  3.61               0             0   

   city_Dubai  ...  color_I  color_J  clarity_I1  clarity_IF  clarity_SI1  \
0           0  ...        0        0           0           0            0   
1           0  ...        0        0           0           0            0   
2           0  ...        0        0           0           0            0   
3           0  ...        0        0           0           0            0   
4           0  ...        0        0           0           0            0   

   clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2  
0            0            0            1             0             0  
1            0            0            1             0             0  
2            0            0            1             0             0  
3            0            0            1             0             0  
4            0            0            1             0             0  

[5 rows x 40 columns]

In [135]:
# creating X and y

X = train_df.drop('price', axis=1)
X.head()

carat  depth  table     x     y     z  city_Amsterdam  city_Antwerp  \
0   1.01   65.2   56.0  6.23  6.19  4.05               1             0   
1   1.51   65.0   64.0  7.10  7.03  4.59               1             0   
2   2.00   65.2   56.0  7.92  7.87  5.15               0             0   
3   1.99   60.5   63.0  8.20  8.11  4.93               0             0   
4   0.70   65.0   56.0  5.60  5.50  3.61               0             0   

   city_Dubai  city_Kimberly  ...  color_I  color_J  clarity_I1  clarity_IF  \
0           0              0  ...        0        0           0           0   
1           0              0  ...        0        0           0           0   
2           0              0  ...        0        0           0           0   
3           0              0  ...        0        0           0           0   
4           0              0  ...        0        0           0           0   

   clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0            0            0            0            1             0   
1            0            0            0            1             0   
2            0            0            0            1             0   
3            0            0            0            1             0   
4            0            0            0            1             0   

   clarity_VVS2  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 39 columns]

In [136]:
y = train_df['price']
y

0         3733
1         9452
2        12765
3        17713
4         2268
         ...  
40450     3193
40451    15898
40452      666
40453     1945
40454     6521
Name: price, Length: 40455, dtype: int64

In [137]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [138]:
#  Data scaling
scaler = RobustScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [139]:
%%time

# Model definition

model = RandomForestRegressor()
model

CPU times: total: 0 ns
Wall time: 0 ns


RandomForestRegressor()

In [142]:
%%time

# Model training

weights = model.fit(X, y)
weights

CPU times: total: 20.4 s
Wall time: 32 s


RandomForestRegressor()

In [119]:
%%time

# Model predictions

predictions = model.predict(X_test)
predictions

CPU times: total: 0 ns
Wall time: 17.7 ms


array([4451.24027668, 2089.76333444, 1784.59232533, ..., 6264.53748459,
       5919.90451904,  650.47410552])

In [120]:
# RMSE

tricky_error = round(mean_squared_error(y_test, predictions)**0.5, 5)
tricky_error

715.1058

In [121]:
%%time

# Model training

weights = model.fit(X_train, y_train)
weights

CPU times: total: 4.47 s
Wall time: 4.48 s


GradientBoostingRegressor()

In [127]:
%%time

# Model predictions

predictions = model.predict(X_test)
predictions

CPU times: total: 31.2 ms
Wall time: 46.9 ms


array([4474.86142952, 2059.20016003, 1663.83314251, ..., 6192.63568386,
       5851.1037623 ,  744.46353398])

In [123]:
# RMSE

real_error = round(mean_squared_error(y_test, predictions)**0.5, 5)
real_error

733.06172

### Test set

In [90]:
# test diamond ML

test_df = pd.read_csv('../data/final_diamonds_test.csv',index_col=[0])
test_df.head()

carat  depth  table     x     y     z  city_Amsterdam  city_Antwerp  \
0   0.79   62.7   60.0  5.82  5.89  3.67               1             0   
1   1.20   61.0   57.0  6.81  6.89  4.18               0             0   
2   1.57   62.2   61.0  7.38  7.32  4.57               0             0   
3   0.90   63.8   54.0  6.09  6.13  3.90               0             0   
4   0.50   62.9   58.0  5.05  5.09  3.19               1             0   

   city_Dubai  city_Kimberly  ...  color_I  color_J  clarity_I1  clarity_IF  \
0           0              0  ...        0        0           0           0   
1           0              0  ...        0        1           0           0   
2           0              1  ...        0        0           0           0   
3           0              1  ...        0        0           0           0   
4           0              0  ...        0        0           0           0   

   clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0            1            0            0            0             0   
1            0            0            1            0             0   
2            1            0            0            0             0   
3            1            0            0            0             0   
4            0            0            1            0             0   

   clarity_VVS2  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 39 columns]

In [91]:
%%time

# Model definition

model = RandomForestRegressor()
model

CPU times: total: 0 ns
Wall time: 0 ns


RandomForestRegressor()

In [92]:
%%time

# Model training

weights = model.fit(X, y)
weights

CPU times: total: 29.1 s
Wall time: 29.3 s


RandomForestRegressor()

In [93]:
# Model predictions

predictions = model.predict(test_df)
predictions

array([3033.87, 5344.45, 9260.66, ..., 2939.1 , 2143.71,  837.76])

In [94]:
# Create a dataframe with the predicted price
predictions_df = pd.DataFrame({'price': predictions})
predictions_df

price
0      3033.87
1      5344.45
2      9260.66
3      4213.07
4      1695.66
...        ...
13480  1674.52
13481  2422.82
13482  2939.10
13483  2143.71
13484   837.76

[13485 rows x 1 columns]

In [95]:
# Set the name of the index as 'id'
predictions_df = predictions_df.rename_axis('id')
predictions_df.head()

price
id         
0   3033.87
1   5344.45
2   9260.66
3   4213.07
4   1695.66

In [96]:
#predictions_df.to_csv('../predictions/predict-6.csv')

In [97]:
predictions_df.to_csv('../predictions/predict-21.csv')