In [3]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import RobustScaler, StandardScaler
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split

from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from sklearn.tree import DecisionTreeRegressor

from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn import linear_model 

### Train set

In [4]:
train_df = pd.read_csv('../data/final_diamonds_train.csv', index_col=[0])
train_df.head()

price  carat  depth  table     x     y     z  city_Amsterdam  city_Antwerp  \
0   3733   1.01   65.2   56.0  6.23  6.19  4.05               1             0   
1   9452   1.51   65.0   64.0  7.10  7.03  4.59               1             0   
2  12765   2.00   65.2   56.0  7.92  7.87  5.15               0             0   
3  17713   1.99   60.5   63.0  8.20  8.11  4.93               0             0   
4   2268   0.70   65.0   56.0  5.60  5.50  3.61               0             0   

   city_Dubai  ...  color_I  color_J  clarity_I1  clarity_IF  clarity_SI1  \
0           0  ...        0        0           0           0            0   
1           0  ...        0        0           0           0            0   
2           0  ...        0        0           0           0            0   
3           0  ...        0        0           0           0            0   
4           0  ...        0        0           0           0            0   

   clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2  
0            0            0            1             0             0  
1            0            0            1             0             0  
2            0            0            1             0             0  
3            0            0            1             0             0  
4            0            0            1             0             0  

[5 rows x 40 columns]

In [5]:
# creating X and y

X = train_df.drop('price', axis=1)
X.head()

carat  depth  table     x     y     z  city_Amsterdam  city_Antwerp  \
0   1.01   65.2   56.0  6.23  6.19  4.05               1             0   
1   1.51   65.0   64.0  7.10  7.03  4.59               1             0   
2   2.00   65.2   56.0  7.92  7.87  5.15               0             0   
3   1.99   60.5   63.0  8.20  8.11  4.93               0             0   
4   0.70   65.0   56.0  5.60  5.50  3.61               0             0   

   city_Dubai  city_Kimberly  ...  color_I  color_J  clarity_I1  clarity_IF  \
0           0              0  ...        0        0           0           0   
1           0              0  ...        0        0           0           0   
2           0              0  ...        0        0           0           0   
3           0              0  ...        0        0           0           0   
4           0              0  ...        0        0           0           0   

   clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0            0            0            0            1             0   
1            0            0            0            1             0   
2            0            0            0            1             0   
3            0            0            0            1             0   
4            0            0            0            1             0   

   clarity_VVS2  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 39 columns]

In [4]:
y = train_df['price']
y

0         3733
1         9452
2        12765
3        17713
4         2268
         ...  
40450     3193
40451    15898
40452      666
40453     1945
40454     6521
Name: price, Length: 40455, dtype: int64

In [5]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
%%time

# Model definition

model = DecisionTreeRegressor()
model

CPU times: total: 0 ns
Wall time: 0 ns


DecisionTreeRegressor()

In [8]:
%%time

# Model training

weights = model.fit(X, y)
weights

CPU times: total: 359 ms
Wall time: 367 ms


DecisionTreeRegressor()

In [9]:
%%time

# Model predictions

predictions = model.predict(X_test)
predictions

CPU times: total: 0 ns
Wall time: 6.78 ms


array([4623., 2696., 1698., ..., 6503., 4896.,  399.])

In [10]:
# RMSE

tricky_error = round(mean_squared_error(y_test, predictions)**0.5, 5)
tricky_error

1.55859

In [11]:
%%time

# Model training

weights = model.fit(X_train, y_train)
weights

CPU times: total: 281 ms
Wall time: 309 ms


DecisionTreeRegressor()

In [12]:
%%time

# Model predictions

predictions = model.predict(X_test)
predictions

CPU times: total: 0 ns
Wall time: 7.97 ms


array([6801., 2511., 1728., ..., 6362., 4986.,  704.])

In [13]:
# RMSE

real_error = round(mean_squared_error(y_test, predictions)**0.5, 5)
real_error

762.46252

In [14]:
# test diamond ML

test_df = pd.read_csv('../data/final_diamonds_test.csv',index_col=[0])
test_df.head()

carat  depth  table     x     y     z  city_Amsterdam  city_Antwerp  \
0   0.79   62.7   60.0  5.82  5.89  3.67               1             0   
1   1.20   61.0   57.0  6.81  6.89  4.18               0             0   
2   1.57   62.2   61.0  7.38  7.32  4.57               0             0   
3   0.90   63.8   54.0  6.09  6.13  3.90               0             0   
4   0.50   62.9   58.0  5.05  5.09  3.19               1             0   

   city_Dubai  city_Kimberly  ...  color_I  color_J  clarity_I1  clarity_IF  \
0           0              0  ...        0        0           0           0   
1           0              0  ...        0        1           0           0   
2           0              1  ...        0        0           0           0   
3           0              1  ...        0        0           0           0   
4           0              0  ...        0        0           0           0   

   clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0            1            0            0            0             0   
1            0            0            1            0             0   
2            1            0            0            0             0   
3            1            0            0            0             0   
4            0            0            1            0             0   

   clarity_VVS2  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 39 columns]

In [15]:
%%time

# Model definition

model = DecisionTreeRegressor()
model

CPU times: total: 0 ns
Wall time: 0 ns


DecisionTreeRegressor()

In [16]:
%%time

# Model training

weights = model.fit(X_train, y_train)
weights

CPU times: total: 297 ms
Wall time: 320 ms


DecisionTreeRegressor()

In [17]:
# Model predictions

predictions = model.predict(test_df)
predictions

array([2816., 5182., 9973., ..., 2790., 1940.,  751.])

In [18]:
# Create a dataframe with the predicted price
predictions_df = pd.DataFrame({'price': predictions})
predictions_df

price
0      2816.0
1      5182.0
2      9973.0
3      4193.0
4      1755.0
...       ...
13480  1613.0
13481  2606.0
13482  2790.0
13483  1940.0
13484   751.0

[13485 rows x 1 columns]

In [19]:
# Set the name of the index as 'id'
predictions_df = predictions_df.rename_axis('id')
predictions_df.head()

price
id        
0   2816.0
1   5182.0
2   9973.0
3   4193.0
4   1755.0

In [20]:
predictions_df.to_csv('../predictions/predict-4.csv')