In [1]:
#import libraries
import pandas as pd
import numpy as np

from sklearn.preprocessing import RobustScaler, StandardScaler
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.model_selection import train_test_split

from sklearn.metrics import roc_auc_score
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn import linear_model 

### Train set

In [2]:
train_df = pd.read_csv('../data/final_diamonds_train.csv', index_col=[0])
train_df.head()

price  carat  depth  table     x     y     z  city_Amsterdam  city_Antwerp  \
0   3733   1.01   65.2   56.0  6.23  6.19  4.05               1             0   
1   9452   1.51   65.0   64.0  7.10  7.03  4.59               1             0   
2  12765   2.00   65.2   56.0  7.92  7.87  5.15               0             0   
3  17713   1.99   60.5   63.0  8.20  8.11  4.93               0             0   
4   2268   0.70   65.0   56.0  5.60  5.50  3.61               0             0   

   city_Dubai  ...  color_I  color_J  clarity_I1  clarity_IF  clarity_SI1  \
0           0  ...        0        0           0           0            0   
1           0  ...        0        0           0           0            0   
2           0  ...        0        0           0           0            0   
3           0  ...        0        0           0           0            0   
4           0  ...        0        0           0           0            0   

   clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  clarity_VVS2  
0            0            0            1             0             0  
1            0            0            1             0             0  
2            0            0            1             0             0  
3            0            0            1             0             0  
4            0            0            1             0             0  

[5 rows x 40 columns]

In [3]:
# creating X and y

X = train_df.drop('price', axis=1)
X.head()

carat  depth  table     x     y     z  city_Amsterdam  city_Antwerp  \
0   1.01   65.2   56.0  6.23  6.19  4.05               1             0   
1   1.51   65.0   64.0  7.10  7.03  4.59               1             0   
2   2.00   65.2   56.0  7.92  7.87  5.15               0             0   
3   1.99   60.5   63.0  8.20  8.11  4.93               0             0   
4   0.70   65.0   56.0  5.60  5.50  3.61               0             0   

   city_Dubai  city_Kimberly  ...  color_I  color_J  clarity_I1  clarity_IF  \
0           0              0  ...        0        0           0           0   
1           0              0  ...        0        0           0           0   
2           0              0  ...        0        0           0           0   
3           0              0  ...        0        0           0           0   
4           0              0  ...        0        0           0           0   

   clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0            0            0            0            1             0   
1            0            0            0            1             0   
2            0            0            0            1             0   
3            0            0            0            1             0   
4            0            0            0            1             0   

   clarity_VVS2  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 39 columns]

In [4]:
y = train_df['price']
y

0         3733
1         9452
2        12765
3        17713
4         2268
         ...  
40450     3193
40451    15898
40452      666
40453     1945
40454     6521
Name: price, Length: 40455, dtype: int64

In [5]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
%%time

# Model definition

model = RandomForestRegressor()
model

CPU times: total: 0 ns
Wall time: 0 ns


RandomForestRegressor()

In [7]:
%%time

# Model training

weights = model.fit(X, y)
weights

CPU times: total: 20.2 s
Wall time: 32.2 s


RandomForestRegressor()

In [8]:
%%time

# Model predictions

predictions = model.predict(X_test)
predictions

CPU times: total: 219 ms
Wall time: 503 ms


array([4676.67, 2617.2 , 1708.94, ..., 6374.34, 4946.22,  453.5 ])

In [9]:
# RMSE

tricky_error = round(mean_squared_error(y_test, predictions)**0.5, 5)
tricky_error

202.15927

In [10]:
%%time

# Model training

weights = model.fit(X_train, y_train)
print(type(weights))

<class 'sklearn.ensemble._forest.RandomForestRegressor'>
CPU times: total: 19 s
Wall time: 26.3 s


In [11]:
%%time

# Model predictions

predictions = model.predict(X_test)
predictions

CPU times: total: 312 ms
Wall time: 519 ms


array([4847.2 , 2511.95, 1729.19, ..., 5993.93, 5024.98,  548.8 ])

In [12]:
# RMSE

real_error = round(mean_squared_error(y_test, predictions)**0.5, 5)
real_error

550.40835

### Test set

In [13]:
# test diamond ML

test_df = pd.read_csv('../data/final_diamonds_test.csv',index_col=[0])
test_df.head()

carat  depth  table     x     y     z  city_Amsterdam  city_Antwerp  \
0   0.79   62.7   60.0  5.82  5.89  3.67               1             0   
1   1.20   61.0   57.0  6.81  6.89  4.18               0             0   
2   1.57   62.2   61.0  7.38  7.32  4.57               0             0   
3   0.90   63.8   54.0  6.09  6.13  3.90               0             0   
4   0.50   62.9   58.0  5.05  5.09  3.19               1             0   

   city_Dubai  city_Kimberly  ...  color_I  color_J  clarity_I1  clarity_IF  \
0           0              0  ...        0        0           0           0   
1           0              0  ...        0        1           0           0   
2           0              1  ...        0        0           0           0   
3           0              1  ...        0        0           0           0   
4           0              0  ...        0        0           0           0   

   clarity_SI1  clarity_SI2  clarity_VS1  clarity_VS2  clarity_VVS1  \
0            1            0            0            0             0   
1            0            0            1            0             0   
2            1            0            0            0             0   
3            1            0            0            0             0   
4            0            0            1            0             0   

   clarity_VVS2  
0             0  
1             0  
2             0  
3             0  
4             0  

[5 rows x 39 columns]

In [14]:
# Model definition

model = LinearRegression()
model

LinearRegression()

In [15]:
%%time

# Model training

weights = model.fit(X_train, y_train)
weights

CPU times: total: 219 ms
Wall time: 219 ms


LinearRegression()

In [16]:
# Model predictions

predictions = model.predict(test_df)
predictions

array([ 3644.96875 ,  6321.609375, 10099.5     , ...,  3902.421875,
        1941.375   ,   745.53125 ])

In [20]:
# Create a dataframe with the predicted price
predictions_df = pd.DataFrame({'price': predictions})
predictions_df

price
0       3644.968750
1       6321.609375
2      10099.500000
3       4633.718750
4       2135.328125
...             ...
13480   1995.187500
13481   2519.593750
13482   3902.421875
13483   1941.375000
13484    745.531250

[13485 rows x 1 columns]

In [21]:
# Set the name of the index as 'id'
predictions_df = predictions_df.rename_axis('id')
predictions_df.head()

price
id              
0    3644.968750
1    6321.609375
2   10099.500000
3    4633.718750
4    2135.328125

In [22]:
predictions_df.to_csv('../predictions/predict-3.csv')